### ISSUE TITLE
The getter 'history' isn't defined for the class '#lib1::NavigatorState'.

### ISSUE THREAD

**Issue by wangqianjun** [FlutterRepo/hybrid_stack_manager#1]
61:48: Error: The getter 'history' isn't defined for the class '#lib1::NavigatorState'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'history'.
compiler message:     List<Route<dynamic>> navHistory = navState.history;

Is there a way to solve this problem?

![image](https://user-images.githubusercontent.com/8085482/44318615-b9c4bd80-a469-11e8-9cb3-25f0ad5cb239.png)

**Comment by realchen** [comment]
大佬，这个最后怎么解决的？
一样的问题

**Comment by Mongolian** [comment]
看之前关闭的问题，解决了的

**Comment by wangqianjun** [comment]
看一下使用说明，里面有注意事项，需要在navigator.dart里面把私有属性history公开出来

**Comment by realchen** [comment]
> 看一下使用说明，里面有注意事项，需要在navigator.dart里面把私有属性history公开出来

已经解决 谢谢
