### ISSUE TITLE
编译错误，，请教大神如何解决？

### ISSUE THREAD

**Issue by ashu0000008** [FlutterRepo/hybrid_stack_manager#19]
![f06f16c4-73d8-4cd8-b718-43d8752142c2](https://user-images.githubusercontent.com/37991077/52996587-0315ba00-3459-11e9-83fe-60cb52c0c307.png)

file:///Users/zhouyang/StudioProjects7/hybrid_stack_manager/lib/router.dart:85:48: Error: The getter 'history' isn't defined for the class '#lib1::NavigatorState'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'history'.
    List<Route<dynamic>> navHistory = navState.history;

**Comment by moonljt521** [comment]
/flutter/packages/flutter/lib/src/widgets/navigator.dart
1318 行添加  List<Route<dynamic>> get history => _history;
