### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by wangqianjun** [FlutterRepo/hybrid_stack_manager#2]
I follow the steps in your documentation integration, but the following error occurs

![image](https://user-images.githubusercontent.com/8085482/44326911-bb08e100-a48f-11e8-8bbf-323f7263fb9b.png)

How to solve this problem?

**Comment by kangwang1988** [comment]
It's a problem related to CocoaPods.
First, Flutter is specified in Podfile as below:
<img width="938" alt="screen shot 2018-08-20 at 7 25 17 pm" src="https://user-images.githubusercontent.com/817851/44338044-49408f80-a4af-11e8-845a-39ae5da323d2.png">

**Comment by wangqianjun** [comment]
Manually add **Header Search Paths** to `hybrid_stack_manager` in `Pods` solved this problem.
`"${PODS_ROOT}/Headers/Public"`

![image](https://user-images.githubusercontent.com/8085482/44398493-93407880-a576-11e8-8437-90ea2e180ede.png)

**Comment by lihaiyin88** [comment]
@wangqianjun I have the same issue, did you resolve it?

**Comment by lihaiyin88** [comment]
@wangqianjun My pods are framework products as the Podfile with "user_framework!". 
When I set the "Framework Search Paths" of the pod target, problem goes on.

**Comment by SinCheung** [comment]
I delete the .podspec.json and then create a .podspec file,  worked it!

**Comment by zhangyangsk8** [comment]
今天试了一下，还是有这个问题！

**Comment by moonljt521** [comment]
> I delete the .podspec.json and then create a .podspec file, worked it!
请问这个 .podspec.json 的文件位置在哪， 还有新建的.podspec file应该在什么位置，它的内容是什么，我是Android dev 不太明白这个~    @SinCheung

**Comment by kangwang1988** [comment]
可以试下0.1.1

**Comment by moonljt521** [comment]
@kangwang1988   thanks

**Comment by kangwang1988** [comment]
0.1.1应该已经修复了这个问题。
