### ISSUE TITLE
The getter 'history' isn't defined for the class 'NagigatorState'

### ISSUE THREAD

**Issue by wangqianjun** [FlutterRepo/hybrid_stack_manager#3]
![image](https://user-images.githubusercontent.com/8085482/44330562-e690c900-a499-11e8-8b6f-49b127cc0e01.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master,`v0.5.8`, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

**Comment by kangwang1988** [comment]
![image](https://user-images.githubusercontent.com/817851/44338522-b1dc3c00-a4b0-11e8-8a02-d4301f4a6d11.png)

View https://pub.dartlang.org/packages/hybrid_stack_manager for more.
