### ISSUE TITLE
Can't find flutter/lib/src/widgets/navigator.dart

### ISSUE THREAD

**Issue by kingstal** [FlutterRepo/hybrid_stack_manager#9]
I can't find flutter/lib/src/widgets/navigator.dart in the project, do you mean router.dart

**Comment by zsmjhtn** [comment]
navigator.dart是在你flutter sdk里面的，这个方案要求你改flutter的sdk源码。原本的_history是私有的，现在强制暴露给外界获取。从方案角度来说可行，从代码角度来说，改源码有点不合适。希望google后续版本自己改下（闲鱼应该会反馈此类需求的吧......）

**Comment by ashu0000008** [comment]
怎么修改源码啊？
